version: '3'

services:
  ms-auth-user:
    container_name: ms-auth-user
    build:
      context: /ms-auth
      dockerfile: Dockerfile
    image: ms-auth-user
    ports:
      - "8081:8081"
    networks:
      - spring-cloud-network
  
  ms-search-recipe:
    container_name: ms-search-recipe
    build:
      context: /ms-search-recipe
      dockerfile: Dockerfile
    image: ms-search-recipe
    ports:
      - "8080:8080"
    networks:
      - spring-cloud-network

  ms-food-planner:
    container_name: ms-food-planner
    build:
      context: /ms-food-planner
      dockerfile: Dockerfile
    image: ms-food-planner
    ports:
      - "8082:8082"
    networks:
      - spring-cloud-network
networks:
  spring-cloud-network:
    driver: bridge