services: 
  ms-search-recipe:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: .
          target: /ms-search-recipe
    environment:
      - spring.data.mongodb.uri=mongodb+srv://admin-govegan:zMtj80lO2iuPb8IT@govegan-cluster.ixmcw2e.mongodb.net/ms-recipe
      - spring.data.mongodb.database=ms-recipe
    restart: always